// Code generated by cmd/generate-lucide; DO NOT EDIT.

package catalog

import (
	"github.com/mirzakhany/yoga/icons"
	"testing"
)

func TestGeneratedCatalog(t *testing.T) {
	if len(All) != 1775 {
		t.Fatalf("len(All) = %d, want 1775", len(All))
	}
	for _, ic := range All {
		if ic.Empty() {
			t.Fatalf("empty icon in catalog")
		}
		if _, err := ic.Alpha(icons.BakePx); err != nil {
			t.Fatalf("%s: %v", ic.Name, err)
		}
	}
}
